Update agent env to support Docker

diff --git a/bin/boot_docker b/bin/boot_docker
--- a/bin/boot_docker
+++ b/bin/boot_docker
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-MAX_ATTEMPTS=50
+MAX_ATTEMPTS=20
 
 docker info > /dev/null 2>&1
 STATUS="$?"
@@ -9,20 +9,25 @@ if [ "$STATUS" != "0" ]; then
     if [ "$(uname)" == "Darwin" ]; then
       echo "Starting Docker..." >&2
       open -a Docker || exit $?
-      ATTEMPTS=1
-      while ! docker info > /dev/null 2>&1; do
-        if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
-          echo "Docker failed to boot; exiting." >&2
-          exit 1
-        fi
-        echo "... (check $ATTEMPTS)"
-        ATTEMPTS=$((ATTEMPTS + 1))
-        sleep 1
-      done
+    elif [ "$(uname)" == "Linux" ]; then
+      echo "Starting Docker..." >&2
+      sudo service docker start || exit $?
     else
       echo "Docker isn't running! Please start Docker and try again." >&2
       exit 1
     fi
+
+    echo "Waiting for Docker to boot..." >&2
+    ATTEMPTS=1
+    while ! docker info > /dev/null 2>&1; do
+      if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
+        echo "Docker failed to boot; exiting." >&2
+        exit 1
+      fi
+      echo "... (check $ATTEMPTS)"
+      ATTEMPTS=$((ATTEMPTS + 1))
+      sleep 1
+    done
   else
     exit 1
   fi
